BEGIN TRANSACTION;
CREATE TABLE "core_grupoitemmenu" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(255) NOT NULL, "ordem" smallint NOT NULL);
INSERT INTO `core_grupoitemmenu` VALUES (1,'RME',1);
INSERT INTO `core_grupoitemmenu` VALUES (2,'Dúvidas',2);
INSERT INTO `core_grupoitemmenu` VALUES (3,'Conta',3);
CREATE INDEX "sitetree_treeitem_dd0f9f4f" ON "sitetree_treeitem" ("access_restricted");
CREATE INDEX "sitetree_treeitem_daef6449" ON "sitetree_treeitem" ("urlaspattern");
CREATE INDEX "sitetree_treeitem_a73f1f77" ON "sitetree_treeitem" ("sort_order");
CREATE INDEX "sitetree_treeitem_a623d47f" ON "sitetree_treeitem" ("inbreadcrumbs");
CREATE INDEX "sitetree_treeitem_a0d0c0e2" ON "sitetree_treeitem" ("access_guest");
CREATE INDEX "sitetree_treeitem_724874d1" ON "sitetree_treeitem" ("alias");
CREATE INDEX "sitetree_treeitem_6be37982" ON "sitetree_treeitem" ("parent_id");
CREATE INDEX "sitetree_treeitem_662f707d" ON "sitetree_treeitem" ("hidden");
CREATE INDEX "sitetree_treeitem_656442a0" ON "sitetree_treeitem" ("tree_id");
CREATE INDEX "sitetree_treeitem_5ea60347" ON "sitetree_treeitem" ("inmenu");
CREATE INDEX "sitetree_treeitem_572d4e42" ON "sitetree_treeitem" ("url");
CREATE INDEX "sitetree_treeitem_0d286676" ON "sitetree_treeitem" ("insitetree");
CREATE INDEX "sitetree_treeitem_070ee996" ON "sitetree_treeitem" ("access_loggedin");
CREATE INDEX "produtos_tag_b306f3fc" ON "produtos_tag" ("produto_id");
CREATE INDEX "produtos_tag_2dbcba41" ON "produtos_tag" ("slug");
CREATE INDEX "produtos_produtoimagem_b306f3fc" ON "produtos_produtoimagem" ("produto_id");
CREATE INDEX "produtos_produtoatributo_b306f3fc" ON "produtos_produtoatributo" ("produto_id");
CREATE INDEX "produtos_produtoatributo_21c4855e" ON "produtos_produtoatributo" ("valor_item_atributo_id");
CREATE INDEX "produtos_produtoatributo_1525a4ee" ON "produtos_produtoatributo" ("atributo_id");
CREATE INDEX "produtos_produto_b21fda97" ON "produtos_produto" ("grupo_atributo_id");
CREATE INDEX "produtos_produto_abfe0f96" ON "produtos_produto" ("usuario_id");
CREATE INDEX "produtos_produto_2dbcba41" ON "produtos_produto" ("slug");
CREATE INDEX "produtos_itematributo_2dbcba41" ON "produtos_itematributo" ("slug");
CREATE INDEX "produtos_itematributo_1525a4ee" ON "produtos_itematributo" ("atributo_id");
CREATE INDEX "produtos_destaque_produtos_b306f3fc" ON "produtos_destaque_produtos" ("produto_id");
CREATE INDEX "produtos_destaque_produtos_3517741a" ON "produtos_destaque_produtos" ("destaque_id");
CREATE INDEX "produtos_categoriaimagem_daf3833b" ON "produtos_categoriaimagem" ("categoria_id");
CREATE INDEX "produtos_categoriabannerimagem_daf3833b" ON "produtos_categoriabannerimagem" ("categoria_id");
CREATE INDEX "produtos_categoria_produtos_daf3833b" ON "produtos_categoria_produtos" ("categoria_id");
CREATE INDEX "produtos_categoria_produtos_b306f3fc" ON "produtos_categoria_produtos" ("produto_id");
CREATE INDEX "produtos_categoria_caf7cc51" ON "produtos_categoria" ("lft");
CREATE INDEX "produtos_categoria_c9e9a848" ON "produtos_categoria" ("level");
CREATE INDEX "produtos_categoria_6be37982" ON "produtos_categoria" ("parent_id");
CREATE INDEX "produtos_categoria_656442a0" ON "produtos_categoria" ("tree_id");
CREATE INDEX "produtos_categoria_3cfbd988" ON "produtos_categoria" ("rght");
CREATE INDEX "produtos_categoria_2dbcba41" ON "produtos_categoria" ("slug");
CREATE INDEX "produtos_atributogrupo_atributos_982165a8" ON "produtos_atributogrupo_atributos" ("atributogrupo_id");
CREATE INDEX "produtos_atributogrupo_atributos_1525a4ee" ON "produtos_atributogrupo_atributos" ("atributo_id");
CREATE INDEX "produtos_atributo_2dbcba41" ON "produtos_atributo" ("slug");
CREATE INDEX "perfis_usuariocompra_produtos_b306f3fc" ON "perfis_usuariocompra_produtos" ("produto_id");
CREATE INDEX "perfis_usuariocompra_produtos_852a8c11" ON "perfis_usuariocompra_produtos" ("usuariocompra_id");
CREATE INDEX "django_session_de54fa62" ON "django_session" ("expire_date");
CREATE INDEX "django_admin_log_e8701ad4" ON "django_admin_log" ("user_id");
CREATE INDEX "django_admin_log_417f1b1c" ON "django_admin_log" ("content_type_id");
CREATE INDEX "core_pagina_2dbcba41" ON "core_pagina" ("slug");
CREATE INDEX "core_noticia_52be3978" ON "core_noticia" ("autor_id");
CREATE INDEX "core_noticia_2dbcba41" ON "core_noticia" ("slug");
CREATE INDEX "core_itemmenu_7d5be05b" ON "core_itemmenu" ("grupo_menu_id");
CREATE INDEX "core_itemmenu_02f97d6d" ON "core_itemmenu" ("pagina_id");
CREATE INDEX "core_historico_abfe0f96" ON "core_historico" ("usuario_id");
CREATE INDEX "core_grupoitemmenu_menus_93e25458" ON "core_grupoitemmenu_menus" ("menu_id");
CREATE INDEX "core_grupoitemmenu_menus_8a4b2fb3" ON "core_grupoitemmenu_menus" ("grupoitemmenu_id");
CREATE INDEX "carrinho_itemcarrinho_b306f3fc" ON "carrinho_itemcarrinho" ("produto_id");
CREATE INDEX "carrinho_itemcarrinho_a4202225" ON "carrinho_itemcarrinho" ("carrinho_id");
CREATE INDEX "carrinho_carrinho_e8701ad4" ON "carrinho_carrinho" ("user_id");
CREATE INDEX "auth_user_user_permissions_e8701ad4" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_8373b171" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "auth_user_groups_e8701ad4" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_0e939a4f" ON "auth_user_groups" ("group_id");
CREATE INDEX "auth_permission_417f1b1c" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_permissions_8373b171" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_group_permissions_0e939a4f" ON "auth_group_permissions" ("group_id");
COMMIT;
